# flake8: noqa.
"""statistic

Revision ID: d28a445c13da
Revises: 4d33664f5801
Create Date: 2025-06-04 18:46:17.992658

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d28a445c13da"
down_revision: Union[str, None] = "4d33664f5801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alias_statistics",
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("total_clicks", sa.Integer(), nullable=False),
        sa.Column("last_hour_clicks", sa.Integer(), nullable=False),
        sa.Column("last_day_clicks", sa.Integer(), nullable=False),
        sa.Column("last_hour_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_day_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_clicked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["alias_id"],
            ["aliases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alias_statistics_alias_id"), "alias_statistics", ["alias_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alias_statistics_alias_id"), table_name="alias_statistics")
    op.drop_table("alias_statistics")
    # ### end Alembic commands ###
